from __future__ import annotations

import json
from pathlib import Path
from typing import Iterable

from .audit import AuditResult, Conflict
from .model import Rule


def render_quantumultx(
    rules: Iterable[Rule], path: str | Path, *, generated_at_utc: str | None = None
) -> None:
    lines = [
        "# GENERATED FILE - DO NOT EDIT",
        "# Generated by RuleForge 0.1.0",
        f"# Generated at {generated_at_utc}" if generated_at_utc else "# Generated at unknown",
        "# This is a filter resource, not a complete Quantumult X profile.",
    ]
    lines.extend(rule.to_quantumultx() for rule in rules)
    output = Path(path)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")


def render_json(value: object, path: str | Path) -> None:
    output = Path(path)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(json.dumps(value, ensure_ascii=False, indent=2) + "\n", encoding="utf-8", newline="\n")


def render_audit(audit: AuditResult, path: str | Path) -> None:
    render_json(audit.to_dict(), path)


def render_conflicts(conflicts: Iterable[Conflict], path: str | Path) -> None:
    lines = [
        "# RuleForge conflict report",
        "",
        "These entries were excluded from the conservative generated list.",
        "Review policy intent before adding an explicit resolver.",
        "",
    ]
    for index, conflict in enumerate(conflicts, start=1):
        left = f"{conflict.left.rule_type},{conflict.left.value} -> {conflict.left.policy} ({conflict.left.source_id})"
        right = f"{conflict.right.rule_type},{conflict.right.value} -> {conflict.right.policy} ({conflict.right.source_id})"
        lines.extend(
            [
                f"## {index}. {conflict.kind} / {conflict.relation}",
                f"- left: `{left}`",
                f"- right: `{right}`",
                "",
            ]
        )
    output = Path(path)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(lines), encoding="utf-8", newline="\n")
