from __future__ import annotations

import json
import re
from collections import Counter, defaultdict
from pathlib import Path
from typing import Iterable

from .audit import AuditResult, Conflict, ResolutionResult
from .model import Rule


_CATEGORY_ORDER = (
    "reject",
    "privacy",
    "alipay",
    "wechat",
    "china-services",
    "china-streaming",
    "china-direct",
    "direct-exception",
    "ai",
    "apple",
    "google-voice",
    "google",
    "microsoft",
    "cloud",
    "social",
    "developer",
    "github",
    "spotify",
    "telegram",
    "tiktok",
    "youtube",
    "netflix",
    "china-media",
    "global-media",
    "proxy-exception",
    "proxy",
)


def _category_sort_key(category: str) -> tuple[int, str]:
    try:
        return _CATEGORY_ORDER.index(category), category
    except ValueError:
        return len(_CATEGORY_ORDER), category


def render_quantumultx(
    rules: Iterable[Rule], path: str | Path, *, generated_at_utc: str | None = None
) -> None:
    lines = [
        "# GENERATED FILE - DO NOT EDIT",
        "# Generated by RuleForge 0.1.0",
        f"# Generated at {generated_at_utc}" if generated_at_utc else "# Generated at unknown",
        "# This is a filter resource, not a complete Quantumult X profile.",
    ]
    lines.extend(rule.to_quantumultx() for rule in rules)
    output = Path(path)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")


def _category_filename(category: str) -> str:
    slug = re.sub(r"[^a-z0-9_-]+", "-", category.lower()).strip("-")
    return f"{slug or 'uncategorized'}.list"


def render_category_filters(
    rules: Iterable[Rule],
    root: str | Path,
    *,
    generated_at_utc: str | None = None,
    relative_prefix: str | None = None,
    category_policies: dict[str, str] | None = None,
) -> list[dict[str, object]]:
    """Render one policy-aware filter file per business category.

    Category files always include the policy column. Quantumult X can use
    ``force-policy`` at the profile boundary, but an ``opt-parser=false``
    remote resource still needs each raw filter line to be a complete rule.
    Keeping the policy in both places makes the resource directly importable
    and leaves ``force-policy`` as an explicit profile-level override.
    """

    grouped: dict[str, list[Rule]] = defaultdict(list)
    for rule in rules:
        grouped[rule.category].append(rule)

    output_root = Path(root)
    output_root.mkdir(parents=True, exist_ok=True)
    for stale_file in output_root.glob("*.list"):
        stale_file.unlink()
    prefix = (relative_prefix or output_root.as_posix()).rstrip("/")
    declared_policies = category_policies or {}
    metadata: list[dict[str, object]] = []
    categories = set(grouped) | set(declared_policies)
    for category in sorted(categories, key=_category_sort_key):
        category_rules = sorted(
            grouped[category],
            key=lambda rule: (rule.rule_type, rule.value, rule.options, rule.policy),
        )
        policies = sorted({rule.policy for rule in category_rules if rule.policy})
        declared_policy = declared_policies.get(category)
        if declared_policy and not policies:
            policies = [declared_policy]
        filename = _category_filename(category)
        lines = [
            "# GENERATED FILE - DO NOT EDIT",
            "# Generated by RuleForge 0.1.0",
            f"# Generated at {generated_at_utc}" if generated_at_utc else "# Generated at unknown",
            f"# Category: {category}",
            f"# Policy: {policies[0]}" if len(policies) == 1 else "# Policy: mixed or unset",
            "# This is a filter resource, not a complete Quantumult X profile.",
        ]
        lines.extend(rule.to_quantumultx(include_policy=True) for rule in category_rules)
        output = output_root / filename
        output.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
        metadata.append(
            {
                "category": category,
                "file": f"{prefix}/{filename}",
                "filename": filename,
                "policy": policies[0] if len(policies) == 1 else None,
                "policies": policies,
                "rule_count": len(category_rules),
                "source_count": len({rule.source_id for rule in category_rules}),
            }
        )
    return metadata


def render_mihomo_category_filters(
    rules: Iterable[Rule],
    root: str | Path,
    *,
    generated_at_utc: str | None = None,
    relative_prefix: str | None = None,
    category_policies: dict[str, str] | None = None,
) -> list[dict[str, object]]:
    """Render policy-free Mihomo classical text providers by category."""

    grouped: dict[str, list[Rule]] = defaultdict(list)
    for rule in rules:
        grouped[rule.category].append(rule)

    output_root = Path(root)
    output_root.mkdir(parents=True, exist_ok=True)
    for stale_file in output_root.glob("*.list"):
        stale_file.unlink()
    prefix = (relative_prefix or output_root.as_posix()).rstrip("/")
    declared_policies = category_policies or {}
    metadata: list[dict[str, object]] = []
    categories = set(grouped) | set(declared_policies)
    for category in sorted(categories, key=_category_sort_key):
        category_rules = sorted(
            grouped[category],
            key=lambda rule: (rule.rule_type, rule.value, rule.options, rule.policy),
        )
        policies = sorted({rule.policy for rule in category_rules if rule.policy})
        declared_policy = declared_policies.get(category)
        if declared_policy and not policies:
            policies = [declared_policy]
        if len(policies) != 1:
            raise ValueError(f"Mihomo category {category!r} must have exactly one policy")
        filename = _category_filename(category)
        lines = [
            "# GENERATED FILE - DO NOT EDIT",
            "# Generated by RuleForge 0.1.0",
            f"# Generated at {generated_at_utc}" if generated_at_utc else "# Generated at unknown",
            f"# Category: {category}",
            f"# Policy: {policies[0]}",
            "# Mihomo classical text provider; policy is assigned by RULE-SET.",
        ]
        lines.extend(rule.to_mihomo() for rule in category_rules)
        output = output_root / filename
        output.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
        metadata.append(
            {
                "category": category,
                "file": f"{prefix}/{filename}",
                "filename": filename,
                "policy": policies[0],
                "policies": policies,
                "rule_count": len(category_rules),
                "source_count": len({rule.source_id for rule in category_rules}),
            }
        )
    return metadata


def _mihomo_policy(policy: object) -> str:
    value = str(policy)
    return {"direct": "DIRECT", "reject": "REJECT", "proxy": "全球加速"}.get(
        value.casefold(), value
    )


def render_mihomo_rule_providers(
    entries: Iterable[dict[str, object]],
    path: str | Path,
    *,
    repository_base_url: str,
) -> None:
    lines = [
        "# GENERATED FILE - DO NOT EDIT",
        "rule-providers:",
    ]
    base_url = repository_base_url.rstrip("/")
    for entry in entries:
        category = str(entry["category"])
        file_path = str(entry["file"]).lstrip("/")
        lines.extend(
            [
                f"  {category}:",
                "    type: http",
                "    behavior: classical",
                "    format: text",
                f"    url: \"{base_url}/{file_path}\"",
                f"    path: ./rule_providers/{category}.list",
                "    interval: 172800",
            ]
        )
    output = Path(path)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")


def render_mihomo_rules(entries: Iterable[dict[str, object]], path: str | Path) -> None:
    lines = ["# GENERATED FILE - DO NOT EDIT", "rules:"]
    for entry in entries:
        lines.append(f"  - RULE-SET,{entry['category']},{_mihomo_policy(entry['policy'])}")
    # Keep the broad CN domain fallback after all explicit business rules.
    # This covers Fake-IP/TUN traffic whose synthetic IP cannot match GEOIP,CN.
    lines.append("  - GEOSITE,cn,DIRECT")
    output = Path(path)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")


def render_filter_remote_conf(
    entries: Iterable[dict[str, object]],
    path: str | Path,
    *,
    repository_base_url: str,
    title: str,
) -> None:
    lines = [
        "# GENERATED FILE - DO NOT EDIT",
        "# Copy the following section into a Quantumult X profile.",
        f"# {title}",
        "",
        "[filter_remote]",
    ]
    base_url = repository_base_url.rstrip("/")
    for entry in entries:
        file_path = str(entry["file"]).lstrip("/")
        url = f"{base_url}/{file_path}"
        fields = [url, f"tag={entry['category']}@RuleForge"]
        policy = entry.get("policy")
        if policy:
            fields.append(f"force-policy={policy}")
        fields.extend(["update-interval=172800", "opt-parser=false", "enabled=true"])
        lines.append(",".join(fields))
    output = Path(path)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")


def render_json(value: object, path: str | Path) -> None:
    output = Path(path)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(json.dumps(value, ensure_ascii=False, indent=2) + "\n", encoding="utf-8", newline="\n")


def render_audit(
    audit: AuditResult,
    path: str | Path,
    *,
    resolution: ResolutionResult | None = None,
) -> None:
    data = audit.to_dict()
    if resolution is not None:
        data["conflict_free_rule_count"] = len(audit.safe_rules)
        data["safe_rule_count"] = len(resolution.rules)
        data["resolved_rule_count"] = len(resolution.rules)
        data["resolution"] = resolution.to_dict()
    render_json(data, path)


def render_conflicts(
    conflicts: Iterable[Conflict],
    path: str | Path,
    *,
    resolution: ResolutionResult | None = None,
) -> None:
    conflict_list = list(conflicts)
    decisions = {}
    if resolution is not None:
        decisions = {id(item.conflict): item for item in resolution.decisions}
    grouped: dict[tuple[str, ...], list[Conflict]] = defaultdict(list)
    for conflict in conflict_list:
        categories = tuple(
            sorted(
                {conflict.left.category, conflict.right.category},
                key=_category_sort_key,
            )
        )
        grouped[categories].append(conflict)
    lines = [
        "# RuleForge conflict report",
        "",
        f"These {len(conflict_list)} entries were evaluated by the source-priority resolver.",
        "Priority: Blackmatrix, direct over reject, specific host rules, and configured business-category boundaries.",
        "Conflicts that match none of these priorities remain unresolved and are excluded.",
        "",
        "## Summary",
        "",
    ]
    for kind, count in sorted(Counter(item.kind for item in conflict_list).items()):
        lines.append(f"- {kind}: {count}")
    if resolution is not None:
        lines.extend(
            [
                f"- resolved: {len(resolution.preferred_decisions)}",
                f"- blackmatrix-preferred: {len(resolution.blackmatrix_decisions)}",
                f"- direct-preferred: {len(resolution.direct_decisions)}",
                f"- specific-preferred: {len(resolution.specific_decisions)}",
                f"- category-preferred: {len(resolution.category_decisions)}",
                f"- protective-reject: {len(resolution.protective_reject_decisions)}",
                f"- unresolved: {len(resolution.unresolved_decisions)}",
            ]
        )
    lines.append("")
    index = 0
    for categories in sorted(grouped, key=lambda item: tuple(_category_sort_key(value) for value in item)):
        label = " ↔ ".join(categories)
        lines.extend([f"## {label}", ""])
        for conflict in grouped[categories]:
            index += 1
            left = f"{conflict.left.rule_type},{conflict.left.value} -> {conflict.left.policy} ({conflict.left.source_id})"
            right = f"{conflict.right.rule_type},{conflict.right.value} -> {conflict.right.policy} ({conflict.right.source_id})"
            decision = decisions.get(id(conflict))
            decision_line = "- decision: `unresolved`"
            if decision is not None and decision.winner is not None:
                winner = f"{decision.winner.rule_type},{decision.winner.value} -> {decision.winner.policy} ({decision.winner.source_id})"
                decision_line = f"- decision: `{decision.decision}` -> `{winner}` ({decision.reason})"
            lines.extend(
                [
                    f"### {index}. {conflict.kind} / {conflict.relation}",
                    f"- left: `{left}`",
                    f"- right: `{right}`",
                    decision_line,
                    "",
                ]
            )
    output = Path(path)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(lines), encoding="utf-8", newline="\n")
