from __future__ import annotations

import json
import re
from collections import Counter, defaultdict
from pathlib import Path
from typing import Iterable

from . import __version__
from .audit import AuditResult, Conflict, ResolutionResult
from .curation import SharedInfrastructureRisk
from .model import Rule
from .routing import category_sort_key, rule_sort_key, rule_specificity_key


def render_quantumultx(
    rules: Iterable[Rule], path: str | Path, *, generated_at_utc: str | None = None
) -> None:
    lines = [
        "# GENERATED FILE - DO NOT EDIT",
        f"# Generated by RuleForge {__version__}",
        f"# Generated at {generated_at_utc}" if generated_at_utc else "# Generated at unknown",
        "# This is a filter resource, not a complete Quantumult X profile.",
    ]
    lines.extend(rule.to_quantumultx() for rule in rules)
    output = Path(path)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")


def _category_filename(category: str) -> str:
    slug = re.sub(r"[^a-z0-9_-]+", "-", category.lower()).strip("-")
    return f"{slug or 'uncategorized'}.list"


def render_category_filters(
    rules: Iterable[Rule],
    root: str | Path,
    *,
    generated_at_utc: str | None = None,
    relative_prefix: str | None = None,
    category_policies: dict[str, str] | None = None,
) -> list[dict[str, object]]:
    """Render one policy-aware filter file per business category.

    Category files always include the policy column. Quantumult X can use
    ``force-policy`` at the profile boundary, but an ``opt-parser=false``
    remote resource still needs each raw filter line to be a complete rule.
    Keeping the policy in both places makes the resource directly importable
    and leaves ``force-policy`` as an explicit profile-level override.
    """

    grouped: dict[str, list[Rule]] = defaultdict(list)
    for rule in rules:
        grouped[rule.category].append(rule)

    output_root = Path(root)
    output_root.mkdir(parents=True, exist_ok=True)
    for stale_file in output_root.glob("*.list"):
        stale_file.unlink()
    prefix = (relative_prefix or output_root.as_posix()).rstrip("/")
    declared_policies = category_policies or {}
    metadata: list[dict[str, object]] = []
    categories = set(grouped) | set(declared_policies)
    for category in sorted(categories, key=category_sort_key):
        category_rules = sorted(
            grouped[category],
            key=lambda rule: (rule_specificity_key(rule), rule.policy),
        )
        policies = sorted({rule.policy for rule in category_rules if rule.policy})
        declared_policy = declared_policies.get(category)
        if declared_policy and not policies:
            policies = [declared_policy]
        filename = _category_filename(category)
        lines = [
            "# GENERATED FILE - DO NOT EDIT",
            f"# Generated by RuleForge {__version__}",
            f"# Generated at {generated_at_utc}" if generated_at_utc else "# Generated at unknown",
            f"# Category: {category}",
            f"# Policy: {policies[0]}" if len(policies) == 1 else "# Policy: mixed or unset",
            "# This is a filter resource, not a complete Quantumult X profile.",
        ]
        lines.extend(rule.to_quantumultx(include_policy=True) for rule in category_rules)
        output = output_root / filename
        output.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
        metadata.append(
            {
                "category": category,
                "file": f"{prefix}/{filename}",
                "filename": filename,
                "policy": policies[0] if len(policies) == 1 else None,
                "policies": policies,
                "rule_count": len(category_rules),
                "source_count": len({rule.source_id for rule in category_rules}),
            }
        )
    return metadata


def render_mihomo_category_filters(
    rules: Iterable[Rule],
    root: str | Path,
    *,
    generated_at_utc: str | None = None,
    relative_prefix: str | None = None,
    category_policies: dict[str, str] | None = None,
) -> list[dict[str, object]]:
    """Render policy-free Mihomo classical text providers by category."""

    grouped: dict[str, list[Rule]] = defaultdict(list)
    for rule in rules:
        grouped[rule.category].append(rule)

    output_root = Path(root)
    output_root.mkdir(parents=True, exist_ok=True)
    for stale_file in output_root.glob("*.list"):
        stale_file.unlink()
    prefix = (relative_prefix or output_root.as_posix()).rstrip("/")
    declared_policies = category_policies or {}
    metadata: list[dict[str, object]] = []
    categories = set(grouped) | set(declared_policies)
    for category in sorted(categories, key=category_sort_key):
        category_rules = sorted(
            grouped[category],
            key=lambda rule: (rule_specificity_key(rule), rule.policy),
        )
        policies = sorted({rule.policy for rule in category_rules if rule.policy})
        declared_policy = declared_policies.get(category)
        if declared_policy and not policies:
            policies = [declared_policy]
        if len(policies) != 1:
            raise ValueError(f"Mihomo category {category!r} must have exactly one policy")
        filename = _category_filename(category)
        lines = [
            "# GENERATED FILE - DO NOT EDIT",
            f"# Generated by RuleForge {__version__}",
            f"# Generated at {generated_at_utc}" if generated_at_utc else "# Generated at unknown",
            f"# Category: {category}",
            f"# Policy: {policies[0]}",
            "# Mihomo classical text provider; policy is assigned by RULE-SET.",
        ]
        lines.extend(rule.to_mihomo() for rule in category_rules)
        output = output_root / filename
        output.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
        metadata.append(
            {
                "category": category,
                "file": f"{prefix}/{filename}",
                "filename": filename,
                "policy": policies[0],
                "policies": policies,
                "rule_count": len(category_rules),
                "source_count": len({rule.source_id for rule in category_rules}),
            }
        )
    return metadata


def _mihomo_policy(policy: object) -> str:
    value = str(policy)
    return {"direct": "DIRECT", "reject": "REJECT", "proxy": "全球加速"}.get(
        value.casefold(), value
    )


def render_mihomo_rule_providers(
    entries: Iterable[dict[str, object]],
    path: str | Path,
    *,
    repository_base_url: str,
) -> None:
    lines = [
        "# GENERATED FILE - DO NOT EDIT",
        "rule-providers:",
    ]
    base_url = repository_base_url.rstrip("/")
    for entry in entries:
        category = str(entry["category"])
        file_path = str(entry["file"]).lstrip("/")
        lines.extend(
            [
                f"  {category}:",
                "    type: http",
                "    behavior: classical",
                "    format: text",
                f"    url: \"{base_url}/{file_path}\"",
                f"    path: ./rule_providers/{category}.list",
                "    interval: 86400",
            ]
        )
    output = Path(path)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")


def render_mihomo_rules(
    entries: Iterable[dict[str, object]],
    path: str | Path,
    *,
    priority_rules: Iterable[Rule] = (),
) -> None:
    lines = ["# GENERATED FILE - DO NOT EDIT", "rules:"]
    ordered_priority_rules = sorted(priority_rules, key=rule_sort_key)
    priority_inserted = False
    entries_list = list(entries)
    security_categories = {"direct-exception", "reject", "privacy"}
    for index, entry in enumerate(entries_list):
        category = str(entry["category"])
        lines.append(f"  - RULE-SET,{category},{_mihomo_policy(entry['policy'])}")
        next_category = (
            str(entries_list[index + 1]["category"])
            if index + 1 < len(entries_list)
            else None
        )
        if (
            ordered_priority_rules
            and category in security_categories
            and next_category not in security_categories
        ):
            lines.extend(
                f"  - {rule.to_mihomo()},{_mihomo_policy(rule.policy)}"
                for rule in ordered_priority_rules
            )
            priority_inserted = True
        if category == "ai":
            # Cover OpenAI domains that are not present in the curated Rule Provider.
            lines.append("  - GEOSITE,openai,AI")
    if ordered_priority_rules and not priority_inserted:
        insertion = 2
        lines[insertion:insertion] = [
            f"  - {rule.to_mihomo()},{_mihomo_policy(rule.policy)}"
            for rule in ordered_priority_rules
        ]
    # Keep the broad CN domain fallback after all explicit business rules.
    # This covers Fake-IP/TUN traffic whose synthetic IP cannot match GEOIP,CN.
    lines.append("  - GEOSITE,cn,DIRECT")
    output = Path(path)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")


def render_quantumultx_priority_overrides(
    rules: Iterable[Rule],
    path: str | Path,
    *,
    generated_at_utc: str | None = None,
) -> None:
    """Render mixed-policy rules that must precede whole category providers."""

    render_quantumultx(
        sorted(rules, key=rule_sort_key),
        path,
        generated_at_utc=generated_at_utc,
    )


def render_filter_remote_conf(
    entries: Iterable[dict[str, object]],
    path: str | Path,
    *,
    repository_base_url: str,
    title: str,
    priority_file: str | None = None,
) -> None:
    lines = [
        "# GENERATED FILE - DO NOT EDIT",
        "# Copy the following section into a Quantumult X profile.",
        f"# {title}",
        "",
        "[filter_remote]",
    ]
    base_url = repository_base_url.rstrip("/")
    priority_line = None
    if priority_file:
        priority_url = f"{base_url}/{priority_file.lstrip('/')}"
        priority_line = ",".join(
            [
                priority_url,
                "tag=priority-overrides@RuleForge",
                "update-interval=86400",
                "opt-parser=false",
                "enabled=true",
            ]
        )
    priority_inserted = False
    entries_list = list(entries)
    security_categories = {"direct-exception", "reject", "privacy"}
    for index, entry in enumerate(entries_list):
        file_path = str(entry["file"]).lstrip("/")
        url = f"{base_url}/{file_path}"
        fields = [url, f"tag={entry['category']}@RuleForge"]
        policy = entry.get("policy")
        if policy:
            fields.append(f"force-policy={policy}")
        fields.extend(["update-interval=86400", "opt-parser=false", "enabled=true"])
        lines.append(",".join(fields))
        next_category = (
            str(entries_list[index + 1]["category"])
            if index + 1 < len(entries_list)
            else None
        )
        if (
            priority_line
            and entry.get("category") in security_categories
            and next_category not in security_categories
        ):
            lines.append(priority_line)
            priority_inserted = True
    if priority_line and not priority_inserted:
        lines.insert(5, priority_line)
    output = Path(path)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")


def render_json(value: object, path: str | Path) -> None:
    output = Path(path)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(json.dumps(value, ensure_ascii=False, indent=2) + "\n", encoding="utf-8", newline="\n")


def render_audit(
    audit: AuditResult,
    path: str | Path,
    *,
    resolution: ResolutionResult | None = None,
    shared_infrastructure_risks: Iterable[SharedInfrastructureRisk] | None = None,
) -> None:
    data = audit.to_dict()
    if shared_infrastructure_risks is not None:
        risks = tuple(shared_infrastructure_risks)
        data["shared_infrastructure_risk_count"] = len(risks)
        data["shared_infrastructure_risks"] = [item.to_dict() for item in risks]
    if resolution is not None:
        data["conflict_free_rule_count"] = len(audit.safe_rules)
        data["safe_rule_count"] = len(resolution.rules)
        data["resolved_rule_count"] = len(resolution.rules)
        data["resolution"] = resolution.to_dict()
    render_json(data, path)


def render_conflicts(
    conflicts: Iterable[Conflict],
    path: str | Path,
    *,
    resolution: ResolutionResult | None = None,
    shared_infrastructure_risks: Iterable[SharedInfrastructureRisk] | None = None,
) -> None:
    conflict_list = list(conflicts)
    risk_list = list(shared_infrastructure_risks or ())
    decisions = {}
    if resolution is not None:
        decisions = {id(item.conflict): item for item in resolution.decisions}
    grouped: dict[tuple[str, ...], list[Conflict]] = defaultdict(list)
    for conflict in conflict_list:
        categories = tuple(
            sorted(
                {conflict.left.category, conflict.right.category},
                key=category_sort_key,
            )
        )
        grouped[categories].append(conflict)
    lines = [
        "# RuleForge conflict report",
        "",
        f"These {len(conflict_list)} entries were evaluated by the business-priority resolver.",
        "Exact conflicts use security, explicit override, specificity, category semantics and same-category source priority; semantic overlaps retain both rules and record first-match ordering.",
        "Conflicts that match none of these priorities remain unresolved and are excluded.",
        "",
        "## Summary",
        "",
    ]
    for kind, count in sorted(Counter(item.kind for item in conflict_list).items()):
        lines.append(f"- {kind}: {count}")
    if resolution is not None:
        lines.extend(
            [
                f"- resolved: {len(resolution.preferred_decisions)}",
                f"- blackmatrix-preferred: {len(resolution.blackmatrix_decisions)}",
                f"- direct-preferred: {len(resolution.direct_decisions)}",
                f"- specific-preferred: {len(resolution.specific_decisions)}",
                f"- category-preferred: {len(resolution.category_decisions)}",
                f"- value-category-preferred: {len(resolution.value_category_decisions)}",
                f"- protective-reject: {len(resolution.protective_reject_decisions)}",
                f"- fallback: {len(resolution.fallback_decisions)}",
                f"- ordered-overlap: {len(resolution.ordered_overlap_decisions)}",
                f"- unresolved: {len(resolution.unresolved_decisions)}",
            ]
        )
    lines.append("")
    index = 0
    for categories in sorted(grouped, key=lambda item: tuple(category_sort_key(value) for value in item)):
        label = " ↔ ".join(categories)
        lines.extend([f"## {label}", ""])
        for conflict in grouped[categories]:
            index += 1
            left = f"{conflict.left.rule_type},{conflict.left.value} -> {conflict.left.policy} ({conflict.left.source_id})"
            right = f"{conflict.right.rule_type},{conflict.right.value} -> {conflict.right.policy} ({conflict.right.source_id})"
            decision = decisions.get(id(conflict))
            decision_line = "- decision: `unresolved`"
            if decision is not None and decision.winner is not None:
                winner = f"{decision.winner.rule_type},{decision.winner.value} -> {decision.winner.policy} ({decision.winner.source_id})"
                decision_line = f"- decision: `{decision.decision}` -> `{winner}` ({decision.reason})"
            lines.extend(
                [
                    f"### {index}. {conflict.kind} / {conflict.relation}",
                    f"- left: `{left}`",
                    f"- right: `{right}`",
                    decision_line,
                    "",
                ]
            )
    if risk_list:
        lines.extend(
            [
                "## Shared infrastructure audit",
                "",
                "| Category | Rule | Risk | Reason | Source |",
                "| --- | --- | --- | --- | --- |",
            ]
        )
        for item in risk_list:
            data = item.to_dict()
            lines.append(
                f"| `{data['category']}` | `{data['rule']}` | `{data['risk']}` | "
                f"`{data['reason']}` | `{data['source_id']}` |"
            )
        lines.append("")
    output = Path(path)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(lines), encoding="utf-8", newline="\n")
